import type { NextPage } from "next";
import Head from "next/head";
import { FaArrowUp } from "@react-icons/all-files/fa/FaArrowUp";
import { FaArrowDown } from "@react-icons/all-files/fa/FaArrowDown";
import { Card, CardBody, CardVotes } from "../components/Card";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";
import { useVotesStore } from "../utils/useVotesStore";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const postList = trpc.useQuery(["posts.get-all"]);
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Fredit App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center p-2">
        <Card>
          {postList ? (
            postList?.data?.map((item) => {
              console.log(item);
              return (
                <CardBody
                  author={item!.User!.name}
                  id={item.id}
                  datePosted={item.datePosted}
                  description={item.description}
                  title={item.title}
                  totalCommentCount={item.votes}
                  onClickHandler={() => router.push(`/posts/${item.id}`)}
                />
              );
            })
          ) : (
            <> There is an Error,Check your connection</>
          )}
        </Card>
      </main>
    </>
  );
};

export default Home;
