import type { NextPage } from "next";
import Head from "next/head";
import { FaArrowUp } from "@react-icons/all-files/fa/FaArrowUp";
import { FaArrowDown } from "@react-icons/all-files/fa/FaArrowDown";
import { Card, CardBody, CardVotes } from "../components/Card";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";
import { useVotesStore } from "../utils/useVotesStore";
import { useSession } from "next-auth/react";
import { useState } from "react";

const Home: NextPage = () => {
  const [descriptionText, setDescriptionText] = useState("");
  const [titleText, setTitleText] = useState("");

  const postMutation = trpc.useMutation(["posts.create-post"]);
  const postList = trpc.useQuery(["posts.get-all"]);
  console.log(postList);
  return (
    <>
      <Head>
        <title>Fredit App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-col items-center justify-center p-5">
        <form
          className="flex flex-col items-center "
          onSubmit={(e) => {
            e.preventDefault();
            postMutation.mutate({
              title: titleText,
              description: descriptionText,
            });
          }}
        >
          <h1> Create Posts </h1>
          <input
            className="border-2 shadow"
            type="text"
            onChange={(e) => setTitleText(e.target.value)}
          />
          <textarea
            className="border-2 shadow"
            value={descriptionText}
            onChange={(e) => setDescriptionText(e.target.value)}
          ></textarea>
          <button type="submit" className="bg-blue-400 p-3 px-5">
            submit
          </button>
        </form>

        <Card>
          {postList ? (
            postList?.data?.map((item) => {
              console.log(item);
              return (
                <CardBody
                  author={item!.User.name}
                  datePosted={item.datePosted.toLocaleDateString()}
                  description={item.description}
                  title={item.title}
                  totalCommentCount={item.votes}
                />
              );
            })
          ) : (
            <> There is an Error</>
          )}
        </Card>
      </main>
    </>
  );
};

export default Home;
