import type { NextPage } from "next";
import Head from "next/head";
import { FaArrowUp } from "@react-icons/all-files/fa/FaArrowUp";
import { FaArrowDown } from "@react-icons/all-files/fa/FaArrowDown";
import { Card } from "../components/Card";
import { Navbar } from "../components/Navbar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex items-center justify-center p-5">
        <Card>
          <div className="flex flex-col items-center justify-center gap-5">
            <FaArrowUp />
            <p>30</p>
            <FaArrowDown />
          </div>
          <div className="flex flex-col justify-center gap-3">
            <header>
              <h1 className="text-3xl">Maulidan</h1>
            </header>
            <div className="flex flex-col  text-gray-600">
              <p className="">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                Ducimus similique officia veniam autem vel facere saepe dolorem
                aspernatur nisi velit! Quasi repellendus earum, doloremque
                ducimus eius eligendi voluptatem atque accusantium id vel ipsum
                eum reiciendis dolor autem at ipsa nobis, blanditiis fugiat
                dolorum inventore deserunt recusandae quae similique. Molestiae,
                blanditiis.
              </p>
            </div>
            <div className="flex gap-3 border-t-2">
              <p>author : fikri fadillah</p>
              <p>date posted: 4h ago</p>
              <p>comments: 32</p>
            </div>
          </div>
        </Card>
      </main>
    </>
  );
};

export default Home;
